import math
pi=3.14
a=math.sin(60)
print(a)
b=math.cos(pi)
print(b)
c=math.tan(90)
print(c)
print('the value of 5^8:'+str(math.pow(5,8)))
d=math.sqrt(400)
print(d)
e=math.floor(23.56)
print(e)
f=math.ceil(23.56)
print(f)
